Fixed a few issues with scriptsÃ

diff --git a/bin/new b/bin/new
--- a/bin/new
+++ b/bin/new
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
 set -euo pipefail
 cd app/
-node bin/ia-new
+if ! node bin/ia-new; then
+    echo -e '\n\nIf you encountered errors, you may need to run `start` to install node packages.'
+fi
